### ISSUE TITLE
Dataset question

### ISSUE THREAD

**Issue by QIANQIAN201** [DataSciencePolimi/BERT-Text-Segmentation#5]
Hello, 
I have one question about the dataset that you used. Could you please tell me where did you find this dataset which contain the label 'two_sentences_in_same_segment'  to show if the two sentence have the same meaning?
I have a project that has to use the same kind of dataset but in French version. Thank you very much!!

**Comment by emrecalisir** [comment]
Hi,

I uploaded a sample file for you. Each document in your dataset needs to be stored as a text file, and for each document, each segment boundary should start with the line ======= 

By using the following function, you will have the data frame object containing the related column.

ConvertSegmentFilesToBertInputs.ipynb > func_convert_files_to_bert_input_df_for_pred

I hope it helps!

**Comment by QIANQIAN201** [comment]
Hi,
Thanks for your file, it is really helpful and clear! Besides, could you
please tell me where did you download the train and test dataset? More
specisfically, did you collect the whole dataset yourself? Like you wrote
sentences and then gave a label true/untrue. If you download the dataset
somewhere, please send me the link, i would like to find if there exists
the same dataset but written in french, which is used to train the model
for calculating the semantic similarity between two french sentences.

PS: Thanks again for the file uploaded!

Best wish,
Qianyu

Emre Calisir <notifications@github.com> 于2020年6月26日周五 下午4:01写道：

**Comment by QIANQIAN201** [comment]
> Hi,
> 
> I uploaded a sample file for you. Each document in your dataset needs to be stored as a text file, and for each document, each segment boundary should start with the line =======
> 
> By using the following function, you will have the data frame object containing the related column.
> 
> ConvertSegmentFilesToBertInputs.ipynb > func_convert_files_to_bert_input_df_for_pred
> 
> I hope it helps!

Hi,
Thanks for your file, it is really helpful and clear! Besides, could you
please tell me where did you download the train and test dataset? More
specisfically, did you collect the whole dataset yourself? Like you wrote
sentences and then gave a label true/untrue. If you download the dataset
somewhere, please send me the link, i would like to find if there exists
the same dataset but written in french, which is used to train the model
for calculating the semantic similarity between two french sentences.

PS: Thanks again for the file uploaded!

**Comment by emrecalisir** [comment]
Hi, it's a database provided by a private project. For this reason, I cannot share.
I do recommend you find the datasets provided by the following Github repo.
https://github.com/pinkeshbadjatiya/neuralTextSegmentation/tree/master/code/data
